target: "LDM.AutoencoderKL.AutoencoderKL"   # 模块名.类名
params:
  dim_out: 128
  evo_dim: 20
  filter_list: [1, 3, 5]
  layer_per_block: 1
  target_width: 128
  num_layers: 3
  hidden_dims: 128
  batch_size: 64