first_stage_config:
  target: "LDM.AutoencoderKL.AutoencoderKL"   # 模块名.类名
  params:
    dim_out: 128
    evo_dim: 20
    filter_list: [1, 3, 5]
    layer_per_block: 1
    target_width: 128
    num_layers: 3
    hidden_dims: 128
    batch_size: 64


cond_stage_config:
  target: "LDM.AutoencoderKL.AutoencoderKL"  # 模块名.类名
  params:
    dim_out: 128
    evo_dim: 20
    filter_list: [ 1, 3, 5 ]
    layer_per_block: 1
    target_width: 128
    num_layers: 3
    hidden_dims: 128
    batch_size: 64

diff_stage_config:
  target: "LDM.LatentDiffusion.LatentDiffusion"
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    image_size: 64
    channels: 3
    monitor: val/loss_simple_ema
    cond_stage_trainable: False  # 条件分支冻结
    concat_mode: False   # 使用cross attention做融合，如果是True,使用拼接方式
    conditioning_key: ,
    scale_factor: 1.0,
    scale_by_std: False,
    in_channels: 3
    out_channels: 3
    model_channels: 256
    attention_resolutions:
      - 8
      - 4
      - 2
    num_res_blocks: 2
    channel_mult:
      - 1
      - 2
      - 3
      - 4
    num_head_channels: 32